### ISSUE TITLE
Points to be addressed

### ISSUE THREAD

**Issue by HereAround** [oscar-system/JToric.jl#16]
1. Are all instances of `using GAP` and `using CapAndHomalg` strictly necessary? In particular, they currently appear (at least) once in every file in the src-folder.
2. Similarly, a few instances of `CapAndHomalg.LoadPackage(` "ToricVarieties" ) (and the same for `JConvex` and `JuliaInterface`) might be redundant (replace by `GAP.LoadPackage()` or alike?)
3. Sometimes (I cannot reliably reproduce this) the version number is correctly detected and sometimes not. Identify the cause.
4. Regroup the content of the src-folder to resemble the content of https://github.com/homalg-project/ToricVarieties_project.
5. Extend tests to `Julia 1.3` and `latest`.

**Comment by fingolfin** [comment]
1. You only need `using GAP` once (e.g. in the "top" file, `src/JToric.jl`), same for `CapAndHomalg`. Also note that `import` and `using` are similar things, you don't need both (see also [this FAQ entry](https://docs.julialang.org/en/v1/manual/faq/#What-is-the-difference-between-%22using%22-and-%22import%22?)
2. Yeah, you only need to load packages once. If you do it in `__init__`, it shouldn't be necessary anywhere else. Also, you don't need to load `JuliaInterface`, it will always be loaded by `GAP.jl`
3. I'll take a look at your code later to see if I have an idea

**Comment by HereAround** [comment]
@fingolfin Thank you for the comments.

Part of this has been addressed in https://github.com/HereAround/JToric/pull/15. However, `runtests.jl` still contains the following:

>  using CapAndHomalg
    GAP.Globals.LoadPackage( GapObj( "JConvex" ) )
    CapAndHomalg.LoadPackage( "ToricVarieties" )

I don't think this is ideal, but could not optimize it.

For instance, I tried to remove `CapAndHomalg`. Since the file starts with `using JToric` I was under the impression this was already present (but maybe, I have to move `using CapAndHomalg` to the init_function?). In any case, merely outcommenting this line leads to an `UndefVarError: GAP not defined`.

I have also tried to replace `CapAndHomalg.LoadPackage( "ToricVarieties" )` by `GAP.Globals.LoadPackage( GapObj( "JConvex" ) )`. This leads to another error:

`Error thrown by GAP: Error, UndefVarError: Julia not defined in JuliaEvalString( command_string );`.

Suggestions?

**Comment by fingolfin** [comment]
The `UndefVarError: GAP not defined` is a bug in GAP.jl (good catch), fix is in  https://github.com/oscar-system/GAP.jl/pull/684 and will be in 0.6.2 (which I hope to release later today).

I have not yet tracked down where the `Error, UndefVarError: Julia` comes from. Might be a similar issue, or different, we'll see.

**Comment by fingolfin** [comment]
By the way, what is `JConvex` and where can I find it?

Note that you ask GAP to load it, but you never check if this was successful. Same for `ToricVarieties`. You may want to use `GAP.Packages.load` or even `GAP.Packages.install` for them, and also add a check on the return values

**Comment by fingolfin** [comment]
The `Error, UndefVarError: Julia` is from a bug in `ToricVarieties`, see  https://github.com/homalg-project/ToricVarieties_project/pull/127

**Comment by fingolfin** [comment]
I just released GAP.jl 0.6.1, so you may want to require that as compat version in Project.toml. Together with homalg-project/ToricVarieties_project#127 this allows removing these lines from `test/runtests.jl`:
```
    # load necessary gap-packages
    using CapAndHomalg
    GAP.Globals.LoadPackage( GapObj( "JConvex" ) )
    CapAndHomalg.LoadPackage( "ToricVarieties" )
```

**Comment by HereAround** [comment]
@fingolfin Thank you for the release and the suggestion. I have a corresponding PR open (https://github.com/HereAround/JToric/pull/24). All, but one job complete successfully (and it looks somewhat odd that this one job failed).

**Comment by HereAround** [comment]
> By the way, what is `JConvex` and where can I find it? UPDATE: OK, found it at https://github.com/homalg-project/ToricVarieties_project/tree/master/JConvex
> 
> Note that you ask GAP to load it, but you never check if this was successful. Same for `ToricVarieties`. You may want to use `GAP.Packages.load` or even `GAP.Packages.install` for them, and also add a check on the return values

That is a good suggestion.

I am very happy to modify the loading. Could you please provide a MWE, ideally including a check on the return value, i.e. if the loading was successful? [Probably this is in the docu of GAP.jl and I missed it...]

**Comment by fingolfin** [comment]
Regarding packages, take a look at https://oscar-system.github.io/GAP.jl/dev/#Managing-GAP-packages -- and then feel free to ask questions not answered there (I am the first to admit that we can and should improve things there; constructive feedback is highly welcome)

**Comment by lkastner** [comment]
The convention in Oscar seems to be to use `ToricVariety` rather than `toric_variety`. I'll change that on my branch, let me know if that is ok. How will we do the migration of the code to Oscar? Should we start a branch now?

**Comment by HereAround** [comment]
That change is absolutely ok for me. Can you not open a PR and we merge into the master branch? Is that against Oscar policies?

**Comment by HereAround** [comment]
I think all of this was addressed and will thus close.
