### ISSUE TITLE
Resolve random (?) failures in CI tests

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/JToric.jl#27]
CI tests in various Julia versions (I've seen 1.4, 1.5, 1.6) have been failing. This usually goes away after restarting. Maybe a race condition?

Here's a backtrace of one such failure; unfortunately it is not very useful:
```
ERROR: Package JToric errored during testing
 [1] pkgerror(msg::String)
   @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:55
 [2] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, julia_args::Cmd, test_args::Cmd, test_fn::Nothing)
   @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1693
 [3] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, test_fn::Nothing, julia_args::Cmd, test_args::Cmd, kwargs::Base.Iterators.Pairs{Symbol, IOContext{Base.PipeEndpoint}, Tuple{Symbol}, NamedTuple{(:io,), Tuple{IOContext{Base.PipeEndpoint}}}})
   @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:343
 [4] test(pkgs::Vector{Pkg.Types.PackageSpec}; io::IOContext{Base.PipeEndpoint}, kwargs::Base.Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:coverage,), Tuple{Bool}}})
   @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:80
 [5] test(; name::Nothing, uuid::Nothing, version::Nothing, url::Nothing, rev::Nothing, path::Nothing, mode::Pkg.Types.PackageMode, subdir::Nothing, kwargs::Base.Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:coverage,), Tuple{Bool}}})
   @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:96
 [6] top-level scope
   @ none:1
```

**Comment by fingolfin** [comment]
Aha, I just noticed this error (coming from GAP) earlier in the log: `Panic in src/sysfiles.c:168: Could not write to stdout (fid 1)`

I know the code this is coming from (I already had a "fight" with it recently). No idea yet what triggers it here, but at least that gives a starting point (and it means the issue is more likely in GAP or GAP.jl than in this package here... but we'll see)

**Comment by HereAround** [comment]
I confirm that rebuild for https://github.com/HereAround/JToric/pull/24 resolved the random failures. I will now rerun the checks for https://github.com/HereAround/JToric/pull/25 and https://github.com/HereAround/JToric/pull/26...

Other than that, each of these PRs look good. I wonder if I should merge these as are? If you want to dig deeper into GAP.jl and propose a fix, it might be useful to have these PRs and then rerun their tests (say twice) to check if these random failures have disappeared. What do you think?

**Comment by HereAround** [comment]
Update - indeed, the random failures disappear for https://github.com/HereAround/JToric/pull/25 and https://github.com/HereAround/JToric/pull/26 after sufficiently many reruns.

**Comment by fingolfin** [comment]
Yeah. I don't think there is a point in leaving any PRs open: I will be able to retrigger them by opening a new PR with arbitrary changes, and possibly re-running the tests.

For now I will try to reproduce this locally with a debug build of GAP, in the hope that I'll learn a bit more about the issue (see https://github.com/gap-system/gap/pull/4633)

**Comment by HereAround** [comment]
Ok. I merged the above.

**Comment by HereAround** [comment]
@fingolfin I have not seen any random failures recently. Maybe this can be closed?
