### ISSUE TITLE
Rename this repository to JToric.jl?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/JToric.jl#39]
Julia convention suggests this, and the Julia package manager requires this, I think (if this package ever is to be registered).

**Comment by fingolfin** [comment]
BTW, don't worry, this won't break existing forks; those can be renamed, too, but don't need to. Also, it won't break existing clones of this repository, GitHub automatically sets up redirects.

**Comment by HereAround** [comment]
Thank you @fingolfin. Done.
